GET http://localhost:3000/books HTTP/1.1

###
GET http://localhost:3000/books/1 HTTP/1.1

###
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
  "autor": "Papu",
  "isbn": "12336",
  "editorial": "Papurri2",
  "paginas": 51
}

###
PUT http://localhost:3000/books/1 HTTP/1.1
Content-Type: application/json

{
  "autor": "Tomi",
  "isbn": "12346",
  "editorial": "Potaxies",
  "paginas": 600
}

###
DELETE http://localhost:3000/books/1 HTTP/1.1